### ISSUE TITLE
zoom button

### ISSUE THREAD

**Issue by Ibrahim-Habib** [TarekVito/FractalMandelbrotSet#1]
Hello Mr TarekVito , I liked this project .
when I run it I couldn't zoom in although I pressed the '+' button.
but I found that you zoom in when the key pressed is '+' so I have to press (shift + '+' button) to zoom
so I suggest to modify your code to enable zooming when key == '+' or key == '='.
wish you the best

**Comment by TarekVito** [comment]
Hi Ibrahim, Thanks for reviewing the code.
It seems that '+' button doesn't work correctly on some machines because it works fine on mine.
I edited the code now to support your idea.
Thanks again.
C u in college :)
